services:
  backend:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.backend
    container_name: healthcare_backend
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data       
    env_file:
      - ../.env                 
    networks:
      - healthcare_network
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile.frontend
    container_name: healthcare_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ../.env                 
    networks:
      - healthcare_network
    restart: unless-stopped

networks:
  healthcare_network:
    driver: bridge

volumes:
  data:
    driver: local