# Use a lightweight Python image
FROM python:3.11-alpine

# Set working directory inside container
WORKDIR /app

# Copy backend files
COPY ./agents /app

# Install system dependencies for SQLite and other packages
RUN apk add --no-cache gcc musl-dev

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt


RUN mkdir -p /app/data

EXPOSE 8000


CMD ["python", "run_server.py"]
